version: "3"
services:
  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: chat-app
    working_dir: /var/www/html
    volumes:
      - ./app/:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./logs/php.log:/var/log/fpm-php.www.log
    networks:
      - internal

  db:
    image: mysql:8.0
    container_name: chat-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_db
      MYSQL_USER: chat
      MYSQL_PASSWORD: chat
    volumes:
      - ./dbdata/:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - internal

  nginx:
    image: nginx:alpine
    container_name: chat-nginx
    ports: 
      - "8000:80"
      - "443:443"
    volumes:
      - ./app/:/var/www/html
      - ./logs/nginx:/var/log/nginx/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - internal

networks:
  internal:
    driver: bridge
volumes:
  dbdata:
    driver: local